pipeline {

agent { node {
    label 'aws'
 }
}
stages {
    stage("checkout") {
        steps{
            checkout scm
        }
    }
    stage("build") {
        steps {
            script{
                app = docker.build("terryyoung1192/nginx", "-f PublicJenkinsJobs-CheckHere4TheSauce/nginxDockerBuild/Dockerfile ./PublicJenkinsJobs-CheckHere4TheSauce/nginxDockerBuild/")
            }
        }
    }
    stage("push") {
        steps {
        script {
            docker.withRegistry( 'https://registry.hub.docker.com', 'dockerhub' ) {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("lastest")
            }
            }
        }
    }
    stage("Docker Image Prune") {
        steps {
            sh "docker image prune -a -f"
        }
    }
    }
}