name: Deploy Lambda and API Gateway

on:
  schedule:
    - cron: '10 10 * * 1-5' # 6am Kickoff

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Show current directory
        run: pwd

      - name: List all files and folders
        run: ls -la
    
      - name: Initialize Terraform
        run: |
          cd APICallApps/helloworldAPI
          terraform init

      - name: Plan Terraform Changes
        run: |
          cd APICallApps/helloworldAPI 
          terraform plan

      - name: Apply Terraform Changes
        run: |
          cd APICallApps/helloworldAPI 
          terraform apply -auto-approve