name: Destroy Lambda and API Gateway

on:
  schedule:
    - cron: '0 1 * * 1-5' # 8pm Kickoff

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Initialize Terraform
        run: |
          cd APICallApps/helloworldAPI
          terraform init

      - name: Plan Terraform Changes
        run: |
          cd APICallApps/helloworldAPI 
          terraform plan

      - name: Destroy Terraform
        run: |
          cd APICallApps/helloworldAPI 
          terraform destroy -auto-approve